### ISSUE TITLE
Wrap Evaluator

### ISSUE THREAD

**Issue by BellJrDev** [Collaborative-SWE-at-Purdue/Registry#1]
Develop a skeleton for the Module Evaluator Provider, which will be realized as an object-oriented wrapper around assets we have inherited from Octavo and Primero.

**Comment by bkanter-purdue** [comment]
Added the Version Dependence to the Evaluator object. Figured it made sense to include that score with the rest of them. 

Accessed using the version_dependence member variable. 
Been merged with the dev branch by @j-leidy 
Should not be difficult to merge, since I really did not make any real changes. Just added a line to the Evaluate function at the very end, then added a function called EvaluateVersionDependence(). Just keeping you informed in case you make any major refactors of the object.
